# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: 'Build & Test'

on:
  #push:
    #branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      working-directory: ./DotNet.GitHubAction
      run: dotnet restore
    - name: Run
      working-directory: ./DotNet.GitHubAction
      run: dotnet run -- \
             --owner erichiller \
             --name gh-action-cs-metrics \
             --branch ${{ github.ref }} \
             --dir ${{ '../test/SampleProject' }} \
             --workspace ${{ '../test/SampleProject' }} 
  
#    - name: Build
#      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
