# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: 'Build & Test'

on:
  #push:
    #branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        working-directory: ./DotNet.GitHubAction
        run: dotnet restore
      - name: Build sample project
        working-directory: ./test/SampleProject/SampleProject
        run: dotnet build
  #    - name: Test output
  #      id: test_output
  #      run: |
  #        echo "summary-title=HELLO" >> $GITHUB_OUTPUT
      - name: Run
        id: cs-metrics
        working-directory: ./DotNet.GitHubAction
        run: |
          dotnet run -- \
               --owner erichiller \
               --name gh-action-cs-metrics \
               --branch ${{ github.ref }} \
               --dir ${{ '../test/SampleProject' }} \
               --workspace ${{ '../test/SampleProject' }} 
      - name: Upload metrics markdown
        uses: actions/upload-artifact@v3
        with:
          name: code-metrics
          path: './test/SampleProject/CODE_METRICS.md'
      
      - name: update repo
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '${{ github.sha }}_${{ github.run_number }}+github-actions[bot]@users.noreply.github.com'
          git add ./test/SampleProject/CODE_METRICS.md
          git commit -m "Updated Code metrics"
          git push
  #    - name: Check Output
  #      run: |
  #        echo ${{ steps.cs-metrics.outputs.summary-title }}
  #        echo ${{ steps.test_output.outputs.summary-title }}
  #        # echo "summary-title=HELLO" >> $GITHUB_OUTPUT
  #    - name: Build
  #      run: dotnet build --no-restore
  #    - name: Test
  #      run: dotnet test --no-build --verbosity normal
  